image: <+artifact.image>
port: 80
replicas: 1
namespace: <+pipeline.stages.DeploytoDev.spec.infrastructure.output.namespace>
env_name: <+pipeline.stages.DeploytoDev.spec.infrastructure.output.environment.variables.namespace>
