apiVersion: apps/v1
kind: Deployment
metadata:
  name: approve-deployment
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: approve
  template:
    metadata:
      labels:
        app: approve
    spec:
      containers:
      - name: approve-container
        image: {{.Values.image}}
        ports:
        - containerPort: {{.Values.port}}
        env:
        - name: APP_ENV
          value: {{.Values.env_name}}
